import { NextResponse } from 'next/server'
import { createClient, createAdminClient } from '@/lib/supabase/server'
import { sendInviteEmail } from '@/lib/supabase/send-invite-email'

export async function POST(request: Request) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorised' }, { status: 401 })

  const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).single()
  if (profile?.role !== 'admin') return NextResponse.json({ error: 'Unauthorised' }, { status: 403 })

  const body = await request.json()
  const { email, full_name, role } = body
  if (!email || !role) return NextResponse.json({ error: 'email and role are required' }, { status: 400 })

  const adminClient = createAdminClient()

  // Create the Supabase auth user (email_confirm:true skips Supabase's own invite email)
  const { data: created, error: createError } = await adminClient.auth.admin.createUser({
    email,
    email_confirm: true,
    user_metadata: { full_name: full_name ?? '', role },
  })

  let userId = created?.user?.id

  if (createError && !createError.message.toLowerCase().includes('already')) {
    return NextResponse.json({ error: createError.message }, { status: 400 })
  }

  if (!userId) {
    const { data: { users } } = await adminClient.auth.admin.listUsers()
    userId = users.find(u => u.email === email)?.id
  }

  if (!userId) return NextResponse.json({ error: 'Could not create or find user.' }, { status: 500 })

  // Store invite record with a 72-hour token (token is auto-generated by DB default)
  const expiresAt = new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString()

  const { data: invite, error: inviteError } = await supabase
    .from('invites')
    .insert({
      email,
      role,
      full_name: full_name ?? null,
      invited_by: user.id,
      invite_expires_at: expiresAt,
    })
    .select('invite_token')
    .single()

  if (inviteError || !invite?.invite_token) {
    return NextResponse.json({ error: 'Could not create invite record.' }, { status: 500 })
  }

  const emailError = await sendInviteEmail(email, full_name ?? null, invite.invite_token)
  if (emailError) return NextResponse.json({ error: `Could not send invite email: ${emailError}` }, { status: 500 })

  return NextResponse.json({ success: true })
}
